import Foundation
import Combine

enum AppLanguage: String, CaseIterable, Identifiable {
    case system, english = "en", chinese = "zh-Hans"
    var id: String { rawValue }
    var label: String {
        switch self {
        case .system: return L("跟随系统")
        case .english: return "English"
        case .chinese: return "简体中文"
        }
    }
    func resolved(preferredLanguages: [String] = Locale.preferredLanguages) -> String {
        if self != .system { return rawValue }
        return preferredLanguages.first?.lowercased().hasPrefix("zh") == true ? "zh-Hans" : "en"
    }
}

extension Notification.Name {
    static let appLanguageDidChange = Notification.Name("MacToys.appLanguageDidChange")
}

/// Shared by SwiftUI and AppKit; changing languages never recreates tool services.
final class Localization: ObservableObject {
    static let shared = Localization()
    @Published var language: AppLanguage {
        didSet {
            defaults.set(language.rawValue, forKey: "app.language")
            lock.lock(); resolvedLanguage = language.resolved(); lock.unlock()
            NotificationCenter.default.post(name: .appLanguageDidChange, object: nil)
        }
    }
    private let defaults: UserDefaults
    private let lock = NSLock()
    private var resolvedLanguage: String
    var code: String { lock.lock(); defer { lock.unlock() }; return resolvedLanguage }
    var locale: Locale { Locale(identifier: code) }

    init(defaults: UserDefaults? = nil) {
        let defaults = defaults ?? (ProcessInfo.processInfo.environment["INPUTSTATS_TEST_HOME"] == nil
            ? .standard : UserDefaults(suiteName: "com.local.inputstats.tests")!)
        self.defaults = defaults
        let language = defaults.string(forKey: "app.language").flatMap(AppLanguage.init(rawValue:)) ?? .system
        self.language = language; resolvedLanguage = language.resolved()
    }

    func text(_ key: String, arguments: [CVarArg] = []) -> String {
        let format = code == "en" ? (Self.english[key] ?? key) : key
        return arguments.isEmpty ? format : String(format: format, locale: locale, arguments: arguments)
    }

    // Chinese keys keep the original interface wording and are the Chinese fallback.
    // English entries are checked for missing keys and matching format placeholders.
    static let english: [String: String] = [
        "笔记": "Notes",
        "选择笔记": "Select note",
        "未命名笔记": "Untitled note",
        "新建笔记": "New note",
        "导出 Markdown": "Export Markdown",
        "删除笔记": "Delete note",
        "笔记标题": "Note title",
        "正在保存…": "Saving…",
        "已保存在本机": "Saved locally",
        "Markdown · ⌘B 加粗 · ⌘I 斜体": "Markdown · ⌘B bold · ⌘I italic",
        "记下临时想法、会议记录或草稿。": "Quick ideas, meeting notes, and drafts.",
        "重试保存": "Retry save",
        "删除这篇笔记？": "Delete this note?",
        "无法导出笔记，请检查目标文件夹的写入权限。": "Could not export this note. Check the destination folder’s permissions.",
        "无法读取笔记，原文件已保留。请检查数据文件夹后重试。": "Could not read notes. The original file was kept. Check the data folder and try again.",
        "笔记过大：每篇最多 512 KB，全部笔记最多 20 MB。请先导出整理。": "Note limit exceeded: 512 KB per note, 20 MB total. Export and shorten the note before saving.",
        "笔记尚未保存，请检查磁盘空间或文件权限。未保存内容仍保留在编辑器中。": "Notes have not been saved. Check disk space or permissions. Unsaved text is still in the editor.",
        "笔记未能保存，原有内容保持不变。请检查磁盘空间或文件权限。": "Could not save notes. Existing content was kept. Check disk space or permissions.",
        "笔记编辑器暂时不可用。已保存的内容仍在本机，可以导出 Markdown。": "The editor is unavailable. Saved notes are still on this Mac and can be exported as Markdown.",
        "笔记尚未保存，已取消退出": "Notes are not saved. Quitting was canceled.",
        "笔记固定在小菜单中，可再添加最多 3 个功能。每次打开默认页签；其他功能仍可在主窗口使用。": "Notes is pinned. Add up to 3 other tools and choose which tab opens by default. All tools remain available in the main window.",
        "输入统计只保存计数，不记录输入原文。待办、长期目标和笔记独立保存，清空统计不会删除它们。可在云端同步中手动备份。": "Input Stats saves counts, never typed text. Todos, goals, and notes are stored separately and kept when statistics are cleared. Back them up manually in Cloud Sync.",
        "待办清单、长期目标与笔记": "Todos, long-term goals, and notes",
        "将替换本机的待办、长期目标、笔记、统计和应用偏好。恢复前会自动备份当前数据，并结束当前防休眠会话。": "This replaces local todos, goals, notes, statistics, and app preferences. Current data will be backed up first. Any active Keep Awake session will end.",
        "%@ 项待办 · %@ 个目标 · %@ 篇笔记 · %@ 条分钟统计": "%@ tasks · %@ goals · %@ notes · %@ minute records",
        "%@ 个目标": "%@ goals",
        "%@ 项待办 · %@ 个目标 · %@ 条分钟统计": "%@ tasks · %@ goals · %@ minute records",
        "1. 创建专用私有仓库": "1. Create a dedicated private repository",
        "2. 创建仓库访问令牌": "2. Create a repository access token",
        "3. 粘贴访问令牌": "3. Paste your access token",
        "GitHub 拒绝访问或请求过于频繁。请确认令牌具有该仓库的 Contents 读写权限，稍后重试。": "GitHub denied access or the rate limit was reached. Check that the token has Contents read and write permission for this repository, then retry later.",
        "GitHub 授权已失效。请断开连接后使用新的令牌授权。": "GitHub authorization has expired or was revoked. Disconnect and connect with a new token.",
        "GitHub 私有仓库": "Private GitHub repository",
        "GitHub 请求失败（%@），请稍后重试。": "GitHub request failed (%@). Try again later.",
        "GitHub 返回的备份信息无效，未修改本机数据。": "GitHub returned invalid backup information. Local data was not changed.",
        "Portman 规则、SSH 密钥、系统授权、登录启动和正在运行的防休眠会话不参与同步。": "Portman rules, SSH keys, system permissions, launch at login, and active Keep Awake sessions are not synced.",
        "上传": "Upload",
        "上传会更新云端快照；恢复会替换本机数据，不自动合并。GitHub 会保留以前的提交版本。": "Uploading updates the cloud snapshot. Restoring replaces local data; it does not merge changes. GitHub keeps previous commits.",
        "上传备份…": "Upload backup…",
        "上传本机备份？": "Upload a backup of this Mac?",
        "上次操作": "Last operation",
        "云端同步": "Cloud Sync",
        "云端备份已发生变化，未覆盖它。请重新检查云端备份后再操作。": "The cloud backup changed and was not overwritten. Check the cloud backup again before retrying.",
        "从云端恢复…": "Restore from cloud…",
        "仓库": "Repository",
        "仓库中还没有 MacToys 备份，请先在原来的机器上上传。": "This repository has no MacToys backup yet. Upload one from your other Mac first.",
        "令牌只保存在这台 Mac 的钥匙串中，不会进入备份。": "Your token stays in this Mac’s Keychain and is never included in backups.",
        "写下你想长期推进的事": "Add something you want to work toward",
        "创建仓库 ↗": "Create repository ↗",
        "删除目标：%@": "Delete goal: %@",
        "删除这个长期目标？": "Delete this long-term goal?",
        "同步内容": "Included in backups",
        "在 GitHub 授权 ↗": "Authorize on GitHub ↗",
        "备份内容无效，未修改本机数据。": "This backup is invalid. Local data was not changed.",
        "备份已上传到私有仓库。": "Backup uploaded to your private repository.",
        "备份时间：%@": "Backup created: %@",
        "备份本机并恢复": "Back up this Mac and restore",
        "备份来自更新版本的 MacToys，请先升级应用。": "This backup requires a newer version of MacToys. Update the app first.",
        "备份超过 25 MB，无法同步。请先导出并整理历史数据。": "The backup exceeds 25 MB. Export and reduce historical data before syncing.",
        "将替换本机的待办、长期目标、统计和应用偏好。恢复前会自动备份当前数据，并结束当前防休眠会话。": "This replaces local tasks, goals, statistics, and preferences. Current data will be backed up first, and any active Keep Awake session will end.",
        "将本机配置和数据上传到私有仓库。已有云端备份会被更新，历史版本仍保留在 GitHub。": "Upload this Mac’s settings and data to the private repository. This updates the existing cloud backup; previous commits remain on GitHub.",
        "尚未填写状态": "No status yet",
        "已恢复备份。恢复前的本机数据保存在「本地备份」中。": "Backup restored. Your previous local data is available in Local Backups.",
        "已移除本机授权，云端备份仍保留。": "Local credentials removed. Your cloud backup is still available.",
        "已连接私有仓库，可以上传或恢复备份。": "Private repository connected. You can upload or restore a backup.",
        "当前状态": "Current status",
        "当前状态（可留空）": "Current status (optional)",
        "待办清单与长期目标": "Tasks and long-term goals",
        "恢复未能完成。本地备份和恢复记录已保留，请检查磁盘空间与文件权限后重试。": "Restore could not finish. Local backups and recovery records were kept. Check disk space and file permissions before retrying.",
        "恢复本地备份…": "Restore local backup…",
        "恢复这份备份？": "Restore this backup?",
        "打开仓库": "Open repository",
        "打开本地备份": "Open local backups",
        "把配置和数据备份到自己的 GitHub 私有仓库，在另一台 Mac 上恢复。仅手动同步，不在后台轮询。": "Back up settings and data to your own private GitHub repository and restore on another Mac. Sync runs only when you request it.",
        "持续记录目标与当前状态，不会自动清除。": "Keep your goals and current status here. Goals are never cleared automatically.",
        "断开连接": "Disconnect",
        "无法访问仓库。请确认仓库已创建，且令牌已获准访问它。": "Cannot access this repository. Check that it exists and your token can access it.",
        "无法访问本机钥匙串（%@），授权信息未能保存或读取。": "Could not save or read credentials in this Mac’s Keychain (%@).",
        "无法读取长期目标，原文件已保留。请检查数据文件夹后重试。": "Could not read long-term goals. The original file was kept. Check the data folder, then retry.",
        "无法连接 GitHub，请检查网络后重试。": "Cannot connect to GitHub. Check your network and try again.",
        "本地备份": "Local Backups",
        "本地数据恢复未完成": "Local recovery could not finish",
        "正在处理…": "Working…",
        "每次恢复前，自动保存当前数据。可以随时选取本地备份恢复。": "Current data is backed up before every restore. You can restore any of these local backups.",
        "添加目标": "Add goal",
        "目标": "Goal",
        "编辑目标：%@": "Edit goal: %@",
        "语言、小菜单、颜色收藏与工具偏好": "Language, Quick Panel, saved colors, and tool preferences",
        "请先粘贴 GitHub 访问令牌并连接仓库。": "Paste a GitHub access token and connect your repository first.",
        "请检查数据文件夹中的 sync-rollback.json 与 SyncBackups。为保留原数据，本次不会继续写入。": "Check sync-rollback.json and SyncBackups in the data folder. No further changes will be made until recovery succeeds.",
        "请输入 GitHub 仓库，格式为 用户名/仓库名。": "Enter a GitHub repository as owner/repository.",
        "请输入目标，并将目标和状态控制在合理长度内。": "Enter a goal and keep the goal and status within the supported length.",
        "输入统计历史（仅计数）": "Input statistics (counts only)",
        "这个仓库不是私有仓库。同步已停止，请选择 Private 仓库。": "This repository is not private. Sync was stopped. Choose a private repository.",
        "连接 GitHub": "Connect GitHub",
        "连接仓库": "Connect repository",
        "选择 Only select repositories，并且只选上面的仓库。Contents 权限设为 Read and write，然后生成令牌。": "Choose Only select repositories and select just this repository. Set Contents to Read and write, then generate the token.",
        "长期目标": "Long-term Goals",
        "长期目标未能保存，请检查磁盘空间或文件权限后重试。": "Could not save long-term goals. Check disk space or file permissions, then retry.",
        "%@ 项待办": "%@ remaining",
        "MacToys · 你的 Mac 工具箱": "MacToys · Tools for your Mac",
        "保存": "Save",
        "保存在本机": "Saved on this Mac",
        "删除": "Delete",
        "删除待办：%@": "Delete task: %@",
        "完成待办：%@": "Complete task: %@",
        "小菜单": "Quick Panel",
        "已完成（%@）": "Completed (%@)",
        "待办": "Todo",
        "待办内容": "Task title",
        "待办已全部完成": "All tasks complete",
        "待办未能保存，请检查磁盘空间或文件权限后重试。": "Could not save tasks. Check disk space or file permissions and try again.",
        "待办清单": "Todo List",
        "待办清单、输入统计、端口转发、屏幕取色、滚轮反转与防止休眠。关闭窗口后继续运行；退出 MacToys 会停止统计、快捷键、滚轮反转和防止休眠，Portman 的连接继续由后台管理。": "Todo List, Input Stats, Port Forwarding, Color Picker, Scroll Reversal, and Keep Awake. Tools stay active with the window closed. Quitting stops counting, shortcuts, scroll reversal, and Keep Awake; Portman connections continue in the background.",
        "新待办": "New task",
        "无法读取待办文件，原文件已保留。请检查数据文件夹后重试。": "Could not read tasks. The original file has been kept. Check the data folder, then retry.",
        "未完成的待办会保留。此操作无法撤销。": "Unfinished tasks will be kept. This cannot be undone.",
        "添加待办": "Add task",
        "添加待办…": "Add a task…",
        "清除": "Clear",
        "清除已完成…": "Clear completed…",
        "清除所有已完成的待办？": "Clear all completed tasks?",
        "编辑待办：%@": "Edit task: %@",
        "记下下一件要做的事": "Add your next task",
        "设置与小菜单配置": "Settings and Quick Panel preferences",
        "输入统计只保存计数，不记录输入原文。待办清单单独保存在本机，清空统计不会删除待办。": "Input Stats saves counts, never typed text. Tasks are saved separately on this Mac; clearing statistics keeps your tasks.",
        "选择 1–4 个功能。每次点击菜单栏图标时，打开默认页签；其他功能仍可在主窗口使用。": "Choose 1–4 tools. Each click on the menu bar icon opens your default tab. All tools remain available in the main window.",
        "选择常用功能": "Choose your tools",
        "默认打开": "Default tab",
        "统计数据读写失败：%@": "Could not read or save input counts: %@",
        "拒绝写入负数统计增量": "Refused to save a negative input delta",
        "无法打开文件": "Could not open the file",
        "%@ · 本机运行": "%@ · On-device",
        "%@ 正在运行。退出它后自动启用，避免重复反转。": "%@ is running. Reversal will resume when it quits.",
        "1 小时": "1 hour",
        "15 分钟": "15 minutes",
        "2 小时": "2 hours",
        "24 小时制": "24-hour",
        "30 分钟": "30 minutes",
        "4 小时": "4 hours",
        "5 分钟刷新 · 本机计数": "5-minute refresh · On-device",
        "Fn 按住、双击锁定与松开后的延迟上屏均会处理。其他语音快捷键可手动切换来源。应用未提供文本时，英文按键会标为估算；中文不使用拼音长度猜测。": "Recognizes Fn hold, double-tap, and delayed dictation text. Select a source manually for other voice shortcuts. When an app does not expose text, Latin keystrokes are estimated; Chinese input is not estimated from Pinyin.",
        "HEX 颜色输入": "HEX color",
        "MacToys · 输入统计、端口转发、屏幕取色、滚轮反转与防止休眠": "MacToys · Input Stats, Portman, Color Picker, Scroll Reversal, Keep Awake",
        "MacToys · 输入验证（临时数据）": "MacToys · Input test (temporary data)",
        "MacToys · 防止休眠已开启（右键可关闭）": "MacToys · Keep Awake is on (right-click to turn off)",
        "MacToys 工具箱": "MacToys toolbox",
        "Portman · 端口转发": "Portman · Port Forwarding",
        "Portman 暂不可用": "Portman is unavailable",
        "Portman 界面进程已退出，请重新连接。": "The Portman view has closed. Reconnect to continue.",
        "Portman 返回了无效地址。": "Portman returned an invalid address.",
        "SSH 主机": "SSH Hosts",
        "sRGB · 8 位": "sRGB · 8-bit",
        "一个汉字计一词 · 字母 / 数字连续串计一词 · 密码区域跳过": "Each CJK character or Latin/digit sequence counts as a word. Password fields are skipped.",
        "下载、演示或远程工作时，保持 Mac 唤醒。": "Keep your Mac awake during downloads, presentations, or remote work.",
        "今天": "Today",
        "从最近颜色移除": "Remove from Recents",
        "你的 Mac 工具箱": "Tools for your Mac",
        "保持唤醒": "Keep awake",
        "偏好与数据": "Preferences & data",
        "全局取色快捷键": "Global shortcut",
        "全选": "Select All",
        "全部计为语音": "Count all as voice",
        "全部计为键盘": "Count all as keyboard",
        "关于 MacToys": "About MacToys",
        "关闭此选项后，屏幕可按系统设置熄灭，Mac 继续运行。": "When off, the display can sleep while your Mac keeps running.",
        "关闭窗口后继续生效；菜单栏右键可快速开关。": "Stays active with the window closed. Right-click the menu bar icon to toggle.",
        "剪切": "Cut",
        "单词": "Words",
        "双指滚动和惯性滚动均不反转。": "Two-finger and momentum scrolling stay unchanged.",
        "反转垂直滚动": "Reverse vertical scrolling",
        "反转已暂停": "Reversal paused",
        "反转水平滚动": "Reverse horizontal scrolling",
        "反转鼠标滚轮": "Reverse mouse wheel",
        "取消": "Cancel",
        "取消收藏": "Unfavorite",
        "取消收藏当前颜色": "Unfavorite color",
        "取色": "Colors",
        "取色后打开颜色面板": "Show color panel after picking",
        "取色后自动复制": "Copy after picking",
        "只保存分钟级计数，不保存输入内容。原 InputStats 历史记录继续保留。": "Saves counts per minute, never your text. Existing InputStats history is kept.",
        "合计": "Total",
        "同时保持屏幕亮起": "Keep display awake too",
        "启动系统放大镜；点击取色，Esc 取消": "Click to pick a color with the system magnifier. Esc cancels.",
        "启用 30 秒验证窗口": "Enable 30-second input test",
        "命令行": "CLI",
        "复制": "Copy",
        "复制 %@": "Copy %@",
        "复制格式": "Copy format",
        "多": "More",
        "好": "OK",
        "字": "characters",
        "字母或数字 + ⌘ / ⌥ / ⌃；Esc 取消。": "Use a letter or digit with ⌘, ⌥, or ⌃. Esc cancels.",
        "字符": "Characters",
        "安全输入区域 · 已跳过": "Secure input · Skipped",
        "密码测试（应当完全跳过）": "Password test (must be skipped)",
        "导出失败": "Export failed",
        "导出每日统计": "Export daily counts",
        "将在 %@ 自动关闭": "Ends at %@",
        "拾取": "Pick",
        "少": "Less",
        "屏幕取色": "Color Picker",
        "工具": "Tools",
        "已关闭": "Off",
        "已关闭 · 使用系统休眠设置": "Off · Using system sleep settings",
        "已复制 %@": "Copied %@",
        "已拾取 %@": "Picked %@",
        "应用 HEX": "Apply HEX",
        "开始输入后，这里会显示统计趋势": "Start typing to see your activity",
        "快捷工具": "Quick tools",
        "快捷键未能注册（%@），可能已被占用。请更换组合键；仍可使用取色按钮。": "Could not register shortcut (%@). It may be in use. Choose another combination or use the pick button.",
        "快捷面板": "Quick Panel",
        "打开 MacToys": "Open MacToys",
        "打开主窗口": "Open window",
        "打开数据文件夹": "Open data folder",
        "把 ⌘V 粘贴计入输入": "Include ⌘V pastes",
        "拾取屏幕上的颜色，用在设计与代码中。": "Pick screen colors for your designs and code.",
        "拾取屏幕颜色": "Pick screen color",
        "拾取屏幕颜色…": "Pick Screen Color…",
        "拾取或复制的颜色会保留在这里，点击色块可再次查看。": "Picked and copied colors appear here. Click a swatch to select it.",
        "持续时间": "Duration",
        "按下组合键…": "Press shortcut…",
        "撤销": "Undo",
        "收藏": "Favorites",
        "收藏已满（64 个），请先移除不需要的颜色。": "Favorites are full (64 colors). Remove a color to add another.",
        "收藏当前颜色": "Favorite color",
        "数据操作失败": "Data operation failed",
        "数量": "Count",
        "无法写入剪贴板，请重试。": "Could not write to the clipboard. Try again.",
        "无法创建滚轮监听，请重试。": "Could not create the scroll listener. Try again.",
        "无法启用防止休眠（系统错误 %@），请重试。": "Could not enable Keep Awake (system error %@). Try again.",
        "无法连接 Portman 后台。请重试，或运行 portman daemon status 查看状态。": "Could not connect to Portman. Retry or run portman daemon status.",
        "无法连接滚轮监听，请检查辅助功能权限后重试。": "Could not connect the scroll listener. Check Accessibility permission and retry.",
        "旧版记录": "Legacy data",
        "时间": "Time",
        "时间格式": "Time format",
        "时间范围": "Time range",
        "普通输入（临时数据）": "Normal input (temporary data)",
        "暂停": "Pause",
        "暂停统计": "Pause counting",
        "暂停输入统计": "Pause Input Stats",
        "更改持续时间会重新计时。关闭窗口后继续生效；菜单栏右键可快速开关。": "Changing the duration restarts the timer. Stays active with the window closed; right-click the menu bar icon to toggle.",
        "最小化": "Minimize",
        "最近保留 24 个颜色，收藏单独保存于本机。HEX、RGB 和 HSL 使用 sRGB；超出其范围的广色域颜色会被截取到可表示范围。": "Keeps 24 recent colors. Favorites are saved separately on this Mac. HEX, RGB, and HSL use sRGB; wider-gamut colors are clipped to its range.",
        "最近颜色": "Recent",
        "未找到 Portman，请先安装或检查 ~/.local/bin/portman。": "Portman was not found. Install it or check ~/.local/bin/portman.",
        "未找到 Python 3，请安装 Portman 的运行环境。": "Python 3 was not found. Install the Portman runtime.",
        "本机 Portman 页面加载失败，请重新连接。": "The local Portman page failed to load. Reconnect to continue.",
        "本机数据": "Local data",
        "来源": "Source",
        "查看 %@": "View %@",
        "正在启动": "Starting",
        "正在录制": "Recording",
        "正在连接本机 Portman…": "Connecting to local Portman…",
        "此应用未提供文本 · 中文不估算": "No accessible text · CJK not estimated",
        "此应用未提供文本 · 按键估算": "No accessible text · Estimated keystrokes",
        "此操作会清空已保存和等待保存的全部计数，无法撤销。": "This deletes all saved and pending counts. It cannot be undone.",
        "此范围包含旧版的删除倒扣记录；历史数据保留原值，新版只累计新增输入。": "Includes legacy records that subtracted deletions. History is unchanged; new counts only include added text.",
        "每日合计": "Daily totals",
        "清空": "Clear",
        "清空…": "Clear…",
        "清空全部历史统计？": "Clear all input history?",
        "清空历史数据…": "Clear history…",
        "清空最近颜色": "Clear recent colors",
        "清空最近颜色？收藏会保留。": "Clear recent colors? Favorites will be kept.",
        "滚轮": "Scroll",
        "滚轮反转": "Scroll Reversal",
        "滚轮反转…": "Scroll Reversal…",
        "滚轮监听已暂停，请重试。": "The scroll listener is paused. Try again.",
        "滚轮监听未能启用，请重试。": "Could not enable the scroll listener. Try again.",
        "滚轮监听未能恢复，请重试。": "Could not resume the scroll listener. Try again.",
        "滚轮设置…": "Scroll Settings…",
        "点击星标收藏常用颜色。": "Click the star to save a favorite color.",
        "现有辅助功能授权未生效": "Accessibility permission is unavailable",
        "用于防止闲置休眠。手动睡眠、合盖与锁屏仍按 macOS 的设置处理。退出后结束，下次启动保持关闭。": "Prevents idle sleep. Manual sleep, lid close, and screen locking follow macOS settings. Quitting ends the session; it stays off after relaunch.",
        "界面测试 · 全局反转已关闭": "UI test · Global reversal disabled",
        "界面测试 · 监听已关闭": "UI test · Input monitoring disabled",
        "界面测试 · 系统防休眠已关闭": "UI test · System sleep prevention disabled",
        "登录时启动 MacToys": "Launch MacToys at login",
        "直到关闭": "Until turned off",
        "直到手动关闭或退出 MacToys": "Until turned off or MacToys quits",
        "窗口": "Window",
        "端口转发": "Port Forwarding",
        "等待可编辑输入区域": "Waiting for an editable field",
        "等待输入": "Waiting for input",
        "粘贴": "Paste",
        "统计": "Stats",
        "统计单位": "Metric",
        "统计尚未保存，已取消退出": "Counts are not saved. Quit cancelled.",
        "统计已暂停": "Counting paused",
        "统计视图每 5 分钟刷新，输入持续记录。": "Charts refresh every 5 minutes. Input is recorded continuously.",
        "继续": "Resume",
        "继续统计": "Resume counting",
        "继续输入统计": "Resume Input Stats",
        "编辑": "Edit",
        "自动 · Fn": "Auto · Fn",
        "自动识别 Fn（豆包 / 系统听写）": "Automatic Fn (Doubao / Dictation)",
        "菜单栏右键也可取色。使用放大镜时，空格显示 RGB，Esc 取消。": "Also available from the menu bar. In the magnifier, Space shows RGB; Esc cancels.",
        "触控板保持系统方向": "Trackpad follows system direction",
        "设置": "Settings",
        "设置…": "Settings…",
        "设置取色快捷键": "Set color picker shortcut",
        "词": "words",
        "语言": "Language",
        "语言 / Language": "Language",
        "语音": "Voice",
        "语音输入 · 按上屏文字统计": "Voice · Counting committed text",
        "请使用字母或数字，加上 ⌘、⌥、⌃ 中的至少一个修饰键。": "Use a letter or digit with at least one of ⌘, ⌥, or ⌃.",
        "请在系统设置的登录项中启用 MacToys。": "Enable MacToys in System Settings → Login Items.",
        "请输入 3 位或 6 位 HEX，例如 #F80 或 #FF8800。": "Enter a 3- or 6-digit HEX color, such as #F80 or #FF8800.",
        "请选择要反转的方向": "Select a direction to reverse",
        "调整颜色": "Adjust color",
        "调整鼠标滚轮，保留触控板的滚动方向。": "Reverse mouse wheel scrolling while keeping the trackpad direction.",
        "跟随系统": "System",
        "辅助功能授权未生效，请在系统设置中检查 MacToys 的权限。": "Accessibility permission is unavailable. Check MacToys in System Settings.",
        "输入来源": "Input source",
        "输入监听未连接，请点重试": "Input listener disconnected · Retry",
        "输入统计": "Input Stats",
        "输入统计、端口转发、屏幕取色、滚轮反转与防止休眠。关闭窗口后继续运行；退出 MacToys 会停止统计、快捷键、滚轮反转和防止休眠，Portman 的连接继续由后台管理。": "Input Stats, Port Forwarding, Color Picker, Scroll Reversal, and Keep Awake. Tools stay active with the window closed. Quitting stops counting, shortcuts, scroll reversal, and Keep Awake; Portman connections continue in the background.",
        "近 %@ 天": "%@ days",
        "近 N 天": "Recent days",
        "近一年": "Year",
        "近一年 · 颜色越深输入越多": "Past year · Darker means more input",
        "近期趋势：%@ 天": "Recent activity: %@ days",
        "这个快捷键未能注册（%@），已保留原设置。请换一个组合键。": "Could not register shortcut (%@). The previous shortcut was kept. Try another combination.",
        "这个颜色无法转换为 sRGB，请重新取色。": "Could not convert this color to sRGB. Pick another color.",
        "退出 MacToys": "Quit MacToys",
        "适用于普通滚轮鼠标。Magic Mouse、连续滚动及其他软件生成的滚动保持原样。方向相对于 macOS 当前设置反转。": "For standard wheel mice. Trackpads, Magic Mouse, continuous scrolling, and software-generated events keep their direction. Reversal is relative to macOS settings.",
        "通用": "General",
        "重新连接": "Reconnect",
        "重试": "Retry",
        "重试连接": "Reconnect",
        "键盘": "Keyboard",
        "键盘输入 · 按新增文字统计": "Keyboard · Counting added text",
        "长文档 · 按键估算": "Long document · Estimated keystrokes",
        "防休眠": "Awake",
        "防休眠时长无效。": "Invalid Keep Awake duration.",
        "防休眠设置…": "Keep Awake Settings…",
        "防止休眠": "Keep Awake",
        "防止休眠…": "Keep Awake…",
        "防止休眠已开启": "Keep Awake is on",
        "隐藏 MacToys": "Hide MacToys",
        "颜色面板": "Color Panel",
        "颜色预览 %@": "Color preview %@",
        "验证密码": "Test password",
        "验证文本": "Test text",
        "鼠标滚轮反转已启用": "Mouse wheel reversal is on",
    ]
}

func L(_ key: String, _ arguments: CVarArg...) -> String {
    Localization.shared.text(key, arguments: arguments)
}
